version: "3"

services:
  terminusdb:
    image: terminusdb/terminusdb-server:dev
    container_name: terminusdb-server
    tty: true
    ports:
      - 6363:6363
    environment:
      - TERMINUSDB_SERVER_PORT=6363
    volumes:
      - ./storage:/app/terminusdb/storage
  semantic_indexer:
    build: .
    ports:
      - "8080:8080"
    environment:
      - TERMINUSDB_CONTENT_ENDPOINT=http://terminusdb:6363
      - OPENAI_KEY=${OPENAI_KEY}
    volumes:
      - ./vector_storage:/app/storage
    command: ["./terminusdb-semantic-indexer", "serve", "--directory", "/app/storage", "--size", ${BUFFER_AMOUNT}]
